### ISSUE TITLE
Typo in the readme

### ISSUE THREAD

**Issue by daniel-dawson** [learn-co-curriculum/sql-complex-joins-readme#31]
The provided table and query for the inner join section do not match the results provided. There are several ways to fix this issue, so I'll leave that to the curric people. For students on this lesson, just be aware the current table they provide, alongside the query they provide, would return 0 rows.

**Comment by maxwellbenton** [comment]
Hi @daniel-dawson,

Thank you for opening this issue. Unfortunately, I am not able to replicate the issue you're experiencing. I've tested the code snippets provided in the inner join section and was able to produce the provided results. I've gone ahead and added an additional note to this lesson detailing the SQL queries required to set up the Teachers and Students tables prior to the Inner Join section. Running the example Join queries using the new setup produces the expected results. This should help prevent confusion in the future.

Since it appears this lesson's code snippets are working, I am going to close this issue. However, if you feel this issue is not resolved or that I've missed something, please feel free to re-open this issue with any other information you can provide and I will be happy to take another look.

Thank you!

**Comment by daniel-dawson** [comment]
Sorry, my memory failed me! I did this lab a while ago so was foggy on what was wrong.  I just redid it to make sure there was something wrong, and the left outer join example fails because we are calling Students.id, when there is no such column as Students.id. It should be Students.student_id I think.

**Comment by maxwellbenton** [comment]
Ah, good catch, thank you, @daniel-dawson! I've adjusted the code snippet in the left outer join so that it'll work with the newly added instructions.

Thank you!
